# Generated by Django 5.2.8 on 2025-11-12 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True, verbose_name='ID пациента')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Имя пациента')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Возраст')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рост (см)')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес (кг)')),
                ('blood_pressure_systolic', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name='Систолическое давление')),
                ('blood_pressure_diastolic', models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)], verbose_name='Диастолическое давление')),
                ('heart_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)], verbose_name='Частота сердечных сокращений')),
                ('cholesterol', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Уровень холестерина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Медицинские данные',
                'verbose_name_plural': 'Медицинские данные',
                'ordering': ['-created_at'],
            },
        ),
    ]
