# Generated by Django 5.2.8 on 2025-12-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='blood_pressure_diastolic',
            field=models.IntegerField(verbose_name='Диастолическое давление'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='blood_pressure_systolic',
            field=models.IntegerField(verbose_name='Систолическое давление'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='cholesterol',
            field=models.FloatField(verbose_name='Уровень холестерина'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='heart_rate',
            field=models.IntegerField(verbose_name='Частота сердечных сокращений'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='height',
            field=models.FloatField(verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='patient_id',
            field=models.CharField(max_length=50, verbose_name='ID пациента'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='weight',
            field=models.FloatField(verbose_name='Вес (кг)'),
        ),
    ]
