# Generated by Django 6.0 on 2025-12-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0002_alter_healthdata_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='patient_gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=10, verbose_name='Пол пациента'),
        ),
    ]
