# Generated by Django 6.0.1 on 2026-02-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0003_healthdata_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='patient_gender',
            field=models.CharField(max_length=20, verbose_name='Пол пациента'),
        ),
    ]
