# Generated by Django 6.0.1 on 2026-02-22 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0004_alter_healthdata_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='patient_gender',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='blood_pressure_diastolic',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)], verbose_name='Диастолическое давление'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='blood_pressure_systolic',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name='Систолическое давление'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='cholesterol',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Уровень холестерина'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='heart_rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)], verbose_name='Частота сердечных сокращений'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='patient_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID пациента'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес (кг)'),
        ),
        migrations.AddIndex(
            model_name='healthdata',
            index=models.Index(fields=['patient_id'], name='health_info_patient_adfd61_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdata',
            index=models.Index(fields=['patient_name'], name='health_info_patient_7c3cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdata',
            index=models.Index(fields=['created_at'], name='health_info_created_80aaa0_idx'),
        ),
    ]
